"""Centralized configuration for the EuroSAT classifier project."""

CONFIG = {
    "seed": 42,
    "device": "cuda",
    "num_classes": 10,
    "class_names": [
        "AnnualCrop",
        "Forest",
        "HerbaceousVeg",
        "Highway",
        "Industrial",
        "Pasture",
        "PermanentCrop",
        "Residential",
        "River",
        "SeaLake",
    ],
    "data": {
        "root": "./data",
        "download_train": True,
        "download_val": False,
        "image_size": 64,
        "mean": [0.3444, 0.3803, 0.4078],
        "std": [0.2038, 0.1367, 0.1147],
        "train_split": 21600,
        "val_split": 5400,
        "batch_size": 32,
        "shuffle_train": True,
        "shuffle_val": False,
        "num_workers": 2,
        "rotation_degrees": 15,
        "crop_scale": [0.8, 1.0],
        "hflip_p": 0.5,
        "vflip_p": 0.5,
        "brightness": 0.2,
        "contrast": 0.2,
        "saturation": 0.2,
    },
    "model": {
        "backbone": "resnet18",
        "weights": "IMAGENET1K_V1",
        "dropout_rate": 0.3,
    },
    "training": {
        "criterion": "cross_entropy",
        "optimizer": "adam",
        "lr": 1e-4,
        "weight_decay": 0.0,
        "epochs": 50,
        "patience": 3,
        "checkpoint_path": "best_model.pth",
        "unfreeze_mode": "layer4_fc",
    },
    "uncertainty": {
        "mc_passes": 20,
        "threshold_min": 0.0,
        "threshold_max": 0.002,
        "threshold_steps": 50,
        "min_recall_for_best_threshold": 0.5,
    },
}
